### ISSUE TITLE
linux ubuntu cli issue

### ISSUE THREAD

**Issue by Connoropolous** [iscc/iscc-cli#65]
hey @titusz (and @vingle) 

We just ran our first tests of Mova app on Ubuntu today, and we ran into this one. 
We might be blocked on deploying to that platform till we can get it sorted. I am not sure how high priority that is for Nic, but would like to find out. 

generating iscc for path /home/wesley/1_Projects/lighthouse-obsession.mp4 with title:  lighthouse
stderr: Traceback (most recent call last):
  File "iscc_cli/cli.py", line 97, in <module>
  File "click/core.py", line 829, in __call__

Error occurred in handler for 'iscc-request': Error: error during iscc generation
    at Socket.<anonymous> (/tmp/.mount_mova-0CebFug/resources/app.asar/dist/iscc.js:94:24)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
stderr:   File "click/core.py", line 760, in main
  File "click/_unicodefun.py", line 126, in _verify_python3_env
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/python3/ for mitigation steps.

This system supports the C.UTF-8 locale which is recommended. You might be able to resolve your issue by exporting the following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
[62677] Failed to execute script 'cli' due to unhandled exception!

iscc gen process exited with code 1

**Comment by titusz** [comment]
Can you confirm that the error also happens if you call the iscc-cli command directly from the command line on the system?

**Comment by Connoropolous** [comment]
we confirmed that `iscc gen` worked with the unbundled iscc cli, so we are going to try tweaking the env vars for the subprocess next
